var id=1;
var myname="Reaksa";
let gender="Male";
let age="20";
const score=100;
// document.write('Value of ID  :'+id+'<br>');
// document.write('Value of Name :'+name+'<br>');
// document.write('Value of gender :'+gender+'<br>');
// document.write('Value of age :'+age+'<br>');
// document.write('Value of score :'+score+'<br>');
console.log('value ID :'+id);
console.log('value Name :'+myname);
console.log('value gender :'+gender);
console.log('value age :'+age);
console.log('value score :'+score);
